### ISSUE TITLE
Is there a way to use this as a way to extract qmg files?

### ISSUE THREAD

**Issue by DexrnZacAttack** [googleprojectzero/SkCodecFuzzer#13]

**Comment by zcheese1** [comment]
The SkCodecFuzzer Tool is primarily designed for fuzzing and testing the Skia graphics library. **It may not directly serve as a tool for extracting or manipulating QMG files used by Samsung.** While QMG files are associated with Samsung's proprietary graphics format, their internal structure and encoding methods are not publicly documented.

To extract or work with QMG files, **you would typically require specialized tools or software provided by Samsung or other third-party developers who have reverse-engineered the format. These tools are often specific to Samsung devices and firmware versions**.

**Comment by DexrnZacAttack** [comment]
Do you happen to know of any tools made by these third-party developers?

**Comment by zcheese1** [comment]
There is a tool named **Qmg2Png**
Another way is to use a Web Service called Samsung Knox
