### ISSUE TITLE
please sloved this problem

### ISSUE THREAD

**Issue by templebournith** [googleprojectzero/SkCodecFuzzer#9]
**I need to know how to do it step by step and what this software is and how to connect the phone.** 
![Screenshot 2022-06-10 094306](https://user-images.githubusercontent.com/107234690/172989155-ab4da940-a1a5-4cea-ac43-3e23ed014a06.jpg)
[

**Comment by j00ru** [comment]
Please refer to the documentation in this repository and the Project Zero blog posts.
